LoadLanguageFile "${NSISDIR}\Contrib\Language files\Russian.nlf"

LangString GameName 0 "Единороги: Экспансия"
LangString GameNameLink 0 "Единороги Экспансия"
LangString GameGameName 0 "Игра Единороги: Экспансия"
LangString PublisherName 0 "Терешенков А.В."
LangString AfterParams 0 ": настройка"
LangString MsgInstError 0 "Ошибка установки игры Единороги: Экспансия"
LangString MsgUninstOK 0 "Игра Единороги: Экспансия успешно удалена"
LangString MsgUninstError 0 "Ошибка удаления игры Единороги: Экспансия!"
