var game ;

function initMap() {
  game = new Game() ;

  game.addPortal(2,15) ;
  game.addCrystal(18,5,270) ;
  game.addCrystal(14,17,180) ;
  game.addEnemy1(16,1) ;
  game.addEnemy1(17,7) ;
  game.addUnicorn(5,14) ;

  game.incEnergy(50) ;

  game.setNewViewPoint(9,14) ;

  game.addMessage("unicorn",5,"$Brief_1_1") ;
  game.addMessage("unicorn",5,"$Brief_1_2") ;
  game.addMessage("unicorn",5,"$Brief_1_3") ;
  game.addMessage("unicorn",5,"$Brief_1_4") ;

  game.allowAction("MakeHarvester") ;

  return true ;
}

function isVictory() {
  return false ;
}

function isDefeat() {
  return false ;
}
