var game ;
var uid1 ;
var uidcrystall ;
var uidenemy1 ;
var uidenemy2 ;

function initMap() {
  game = new Game() ;

  game.addPortal(2,15) ;
  game.addCrystal(18,5,1200) ;
  uidcrystall = game.addCrystal(9,18,1500) ;
  uid1 = game.addUnicorn(7,14) ;

  game.incEnergy(80) ;

  game.setNewViewPoint(9,15) ;

  game.addMessage("unicorn",10,"$Brief_1_1") ;
  game.addMessageLater("unicorn",10,10,"$Brief_1_2") ;
  game.addMessageLater("unicorn",10,20,"$Brief_1_3") ;
  game.addMessageLater("unicorn",10,30,"$Brief_1_4") ;
  game.addNewTask("moving","$Task_Moving") ;

  return true ;
}

function Update() {
  if (!game.isFlag("stage2")) {
    if (game.isUnitNearXY(uid1,9,18)) {
      game.setFlag("stage2") ;
      game.setTaskCompleted("moving") ;
      game.addNewTask("makeharvest","$Task_MakeHarvest") ;
      game.addMessage("unicorn",10,"$Brief_2") ;
      game.allowAction("MakeHarvester") ;
    }
  }

  if (game.isFlag("stage2")&&(!game.isFlag("stage3"))) {
      if (game.getUnitHealth(uidcrystall)<1500) {
        game.setFlag("stage3") ;
        game.setTaskCompleted("makeharvest") ;
        game.addNewTask("harvest","$Task_Harvest") ;
        game.addMessage("unicorn",10,"$Brief_3") ;
      }
  }

  if (game.isFlag("stage3")&&(!game.isFlag("stage4"))) {
      if (game.getEnergy()>=100) {
        game.setFlag("stage4") ;
        game.setTaskCompleted("harvest") ;
        game.addNewTask("makeunicorn","$Task_MakeUnicorn") ;
        game.addMessage("unicorn",10,"$Brief_4") ;
        game.allowAction("BuildUnicorn") ;
      }
  }

  if (game.isFlag("stage4")&&(!game.isFlag("stage5"))) {
      if (game.getCountByComponent("Unicorn")==2) {
        game.setFlag("stage5") ;
        game.setTaskCompleted("makeunicorn") ;
        game.addNewTask("battle","$Task_Battle") ;
        game.addMessage("unicorn",10,"$Brief_5_1") ;
        game.addMessageLater("unicorn",10,10,"$Brief_5_2") ;
        game.addMessageLater("unicorn",10,20,"$Brief_5_3") ;
        game.allowAction("MakeAttacker") ;
        game.startTimer(40) ;
      }
  }

  if (game.isFlag("stage5")&&(!game.isFlag("stage6"))) {
    if (game.getTimer()<=0) {
        game.setFlag("stage6") ;
        uidenemy1 = game.addEnemy1(5,12) ;
        uidenemy2 = game.addEnemy1(8,16) ;
    }
  }

  if (game.isFlag("stage6")&&(!game.isFlag("stage7"))) {
    if ((!game.isUnitExist(uidenemy1))&&(!game.isUnitExist(uidenemy2))) {
        game.setFlag("stage7") ;
        game.setTaskCompleted("battle") ;
        game.addNewTask("harvestfinal","$Task_HarvestFinal") ;
        game.addMessage("unicorn",10,"$Brief_7_1") ;
        game.addMessageLater("unicorn",10,10,"$Brief_7_2") ;
    }
  }

  if (game.isFlag("stage7")&&(!game.isFlag("stage8"))) {
      if (game.getEnergy()>=500) {
        game.setFlag("stage8") ;
        game.setTaskCompleted("harvestfinal") ;
        game.addMessage("unicorn",10,"$Brief_8_1") ;
        game.addMessageLater("unicorn",10,10,"$Brief_8_2") ;
        game.addMessageLater("unicorn",10,20,"$Brief_8_3") ;
        game.allowAction("MakeHealer") ;
        game.addEnemy2(16,1) ;
        game.addEnemy1(17,7) ;
      }
  }

}

function isVictory() {
  return false ;
}

function isDefeat() {
  return false ;
}
