var game ;
var TIME_DEFEND ;
 
function initMap() {
  game = new Game() ;

  game.allowAction("MakeHarvester") ;
  game.allowAction("MakeAttacker") ;
  game.allowAction("MakeHealer") ;
  game.allowAction("MakeRadar") ;
  game.allowAction("DoRadar") ;
  game.allowAction("UpgradeHarvester") ;
  game.allowAction("UpgradeAttacker") ;
  game.allowAction("UpgradeHealer") ;
  game.allowAction("MakeShield") ;
  game.allowAction("DoShield") ;
  game.allowAction("MakeTowerAttack") ;
  game.allowAction("MakeTowerHealer") ;
  game.allowAction("MakeTowerHarvest") ;
  game.allowAction("BuildUnicorn") ;
  game.allowAction("ResearchWorkInAction") ;
  game.allowAction("ResearchMagicEconomy") ;
  game.allowAction("ConstructMachine") ;
  game.allowAction("IncreaseUnicornCount") ;
  game.allowAction("ResearchFastBuild") ;
  game.allowAction("SetupBaseShield") ;

  game.addPortal(14,4) ;
  game.addAcademy(18,5) ;
  game.addMachinary(10,6) ;
  game.addUnicorn(14,7) ;
  game.addUnicorn(16,8) ;
  game.addUnicorn(12,9) ;
  game.addCrystalPoor(35,14,80) ;
  game.addCrystalPoor(38,20,85) ;
  game.addCrystalPoor(34,25,55) ;
  game.addCrystal(36,30,50) ;
  game.addCrystalPoor(37,36,135) ;
  game.addCrystalPoor(32,37,130) ;
  game.addCrystalPoor(39,15,95) ;
  game.addCrystal(42,21,35) ;
  game.addCrystalPoor(40,23,80) ;
  game.addCrystalPoor(39,31,44) ;
  game.addCrystal(41,35,60) ;
  game.addCrystal(38,38,65) ;

  game.incEnergy(1000) ;

  TIME_DEFEND = 2;
  if (game.isHard1()) { TIME_DEFEND+=2 ; }
  if (game.isHard2()) { TIME_DEFEND+=2 ; }
  game.startHiddenTimer(TIME_DEFEND*60) ;

  game.setNewViewPoint(14,6) ;

  game.addMessage("unicorn",10,"$Brief_1_1") ;
  game.addMessageLater("unicorn",10,10,"$Brief_1_2") ;
  game.addNewTask("defend","$Task") ;

  return true ;
}

function Update() {
  if ((game.getTimer()<TIME_DEFEND*60-60-30)&&(!game.isFlag("wave1"))) {
     game.addMessage("unicorn",10,"$Brief_2") ;
     game.setFlag("wave1") ;

     var uids = [] ;
     uids.push(game.addEnemy1(39,10)) ;
     uids.push(game.addEnemy1(39,11)) ;
     uids.push(game.addEnemy2(39,12)) ;
     uids.push(game.addEnemy1(39,13)) ;

     uids.push(game.addEnemy1(1,39)) ;
     uids.push(game.addEnemy1(2,39)) ;
     uids.push(game.addEnemy2(3,39)) ;
     uids.push(game.addEnemy1(4,39)) ;

     uids.push(game.addEnemy1(39,25)) ;
     uids.push(game.addEnemy2(38,26)) ;
     uids.push(game.addEnemy2(37,27)) ;
     uids.push(game.addEnemy1(36,28)) ;

     for (var uid in uids) {
       game.setTargetToUnit(uid,14,4) ;
     }
  }

  if ((game.getTimer()<TIME_DEFEND*60-3*60-20)&&(!game.isFlag("wave2"))) {
     game.addMessage("unicorn",10,"$Brief_3") ;
     game.setFlag("wave2") ;

     var uids = [] ;
     uids.push(game.addEnemy3(39,10)) ;
     uids.push(game.addEnemy2(39,11)) ;
     uids.push(game.addEnemy2(39,12)) ;
     uids.push(game.addEnemy3(39,13)) ;

     uids.push(game.addEnemy1(1,39)) ;
     uids.push(game.addEnemy2(2,39)) ;
     uids.push(game.addEnemy2(3,39)) ;
     uids.push(game.addEnemy1(4,39)) ;

     uids.push(game.addEnemy1(39,25)) ;
     uids.push(game.addEnemy2(38,26)) ;
     uids.push(game.addEnemy2(37,27)) ;
     uids.push(game.addEnemy1(36,28)) ;

     for (var uid in uids) {
       game.setTargetToUnit(uid,14,4) ;
     }
  }

  if ((game.getTimer()<TIME_DEFEND*60-5*60-10)&&(!game.isFlag("wave3"))) {
     game.addMessage("unicorn",10,"$Brief_4") ;
     game.setFlag("wave3") ;

     var uids = [] ;
     uids.push(game.addEnemy3(39,10)) ;
     uids.push(game.addEnemy3(39,11)) ;
     uids.push(game.addEnemy3(39,12)) ;
     uids.push(game.addEnemy3(39,13)) ;

     uids.push(game.addEnemy3(1,39)) ;
     uids.push(game.addEnemy2(2,39)) ;
     uids.push(game.addEnemy2(3,39)) ;
     uids.push(game.addEnemy3(4,39)) ;

     uids.push(game.addEnemy3(39,25)) ;
     uids.push(game.addEnemy2(38,26)) ;
     uids.push(game.addEnemy2(37,27)) ;
     uids.push(game.addEnemy3(36,28)) ;

     for (var uid in uids) {
       game.setTargetToUnit(uid,14,4) ;
     }
  }

  if ((game.getTimer()<1)&&(!game.isFlag("final"))) {
     game.addUnicorn(13,3) ;
     game.addUnicorn(14,3) ;
     game.addUnicorn(13,4) ;
     game.setNewViewPoint(14,6) ;
     game.addMessage("unicorn",10,"$Brief_Final") ;
     game.setFlag("final") ;
  }
}

function isVictory() {
  return (game.getTimer()<=0) ;
}

function isDefeat() {
  if (game.getCountByComponent("Portal")==0) { return true ; }
  return false ;
}
