var game ;
var uidrich ;
var uidcave1 ;
var uidcave2 ;
var uidcave3 ;
 
function initMap() {
  game = new Game() ;

  game.allowAction("MakeHarvester") ;
  game.allowAction("MakeAttacker") ;
  game.allowAction("MakeHealer") ;
  game.allowAction("MakeRadar") ;
  game.allowAction("DoRadar") ;
  game.allowAction("UpgradeHarvester") ;
  game.allowAction("UpgradeAttacker") ;
  game.allowAction("UpgradeHealer") ;
  game.allowAction("MakeShield") ;
  game.allowAction("DoShield") ;
  game.allowAction("MakeTowerAttack") ;
  game.allowAction("MakeTowerHealer") ;
  game.allowAction("MakeTowerHarvest") ;
  game.allowAction("BuildUnicorn") ;
  game.allowAction("ResearchWorkInAction") ;
  game.allowAction("ResearchMagicEconomy") ;
  game.allowAction("ConstructMachine") ;
  game.allowAction("IncreaseUnicornCount") ;
  game.allowAction("ResearchFastBuild") ;
  game.allowAction("SetupBaseShield") ;
  game.allowAction("BuildAcademy") ;
  game.allowAction("BuildMachinary") ;

  game.addPortal(13,32) ;

  uidrich = game.addCrystalRich(37,37,7000) ;
  uidcave1 = game.addLair(10,7,"aa") ;
  uidcave2 = game.addLair(11,10,"aa") ;
  uidcave3 = game.addLair(14,8,"aa") ;

  game.incEnergy(400) ;

  game.setNewViewPoint(13,32) ;

  game.addMessage("unicorn",10,"$Brief_1_1") ;
  game.addMessageLater("unicorn",10,10,"$Brief_1_2") ;
  game.addNewTask("rich","$MainTask") ;
  game.addNewTask("caves","$SecondTask") ;

  return true ;
}

function Update() {
  if ((!game.isUnitExist(uidcave1))&&
     (!game.isUnitExist(uidcave2))&&
     (!game.isUnitExist(uidcave3))&&
     (!game.isFlag("nocaves"))) {
     game.setFlag("nocaves") ;
     game.setTaskCompleted("caves") ;
     game.addMessage("unicorn",10,"$Brief_2") ;
  }

  if ((!game.isUnitExist(uidrich))&&(!game.isFlag("rich"))) {
     game.setFlag("rich") ;
     game.addMessage("unicorn",10,"$Brief_3") ;
  }
}

function isVictory() {
  return game.isFlag("rich") ;
}

function isDefeat() {
  if ((game.getCountByComponent("Unicorn")==0)&&
      (game.getCountByComponent("Portal")==0)) { return true ; }
  return false ;
}
