var game ;
var uidhero ;
var uidm1 ;
var uidm2 ;
var uidm3 ;
var find_count ;
 
function initMap() {
  game = new Game() ;

  game.allowAction("MakeHarvester") ;
  game.allowAction("MakeAttacker") ;
  game.allowAction("MakeHealer") ;
  game.allowAction("MakeRadar") ;
  game.allowAction("DoRadar") ;
  game.allowAction("UpgradeHarvester") ;
  game.allowAction("UpgradeAttacker") ;
  game.allowAction("UpgradeHealer") ;
  game.allowAction("MakeShield") ;
  game.allowAction("DoShield") ;
  game.allowAction("MakeTowerAttack") ;
  game.allowAction("MakeTowerHealer") ;
  game.allowAction("MakeTowerHarvest") ;

  game.addPortal(56,37) ;
  uidhero = game.addUnicorn(3,3) ;
  game.addCrystal(36,9,43) ;
  game.addCrystal(11,15,78) ;
  game.addCrystal(56,24,56) ;

  uidm1 = game.addEmptyUnit(27,2,100,"Machine","machine") ;
  uidm2 = game.addEmptyUnit(58,1,100,"Machine","machine") ;
  uidm3 = game.addEmptyUnit(4,20,100,"Machine","machine") ;

  game.addEnemy1(47,12) ;
  game.addEnemy1(33,22) ;
  game.addEnemy1(5,30) ;
  if (game.isHard1()) {
    game.addEnemy2(45,13) ;
  }
  if (game.isHard2()) {
    game.addEnemy2(32,21) ;
  }

  game.addEnemy1(40,35) ;
  game.addEnemy1(42,34) ;
  game.addEnemy1(37,34) ;
  game.addEnemy1(40,38) ;
  game.addEnemy2(42,36) ;
  game.addEnemy2(38,37) ;
  if (game.isHard1()) {
    game.addEnemy2(42,38) ;
    game.addEnemy2(36,35) ;
  }
  if (game.isHard2()) {
    game.addEnemy3(38,35) ;
    game.addEnemy3(37,38) ;
  }

  game.incEnergy(100) ;

  game.setNewViewPoint(8,5) ;

  find_count = 0 ;

  game.addMessage("unicorn",10,"$Brief_1") ;
  game.addNewTask("findportal","$Task1") ;
  return true ;
}

function Update() {
  if (!game.isFlag("point1")) {
    if (game.isUnitNearXYDist(uidhero,27,2,4)) {
      game.setFlag("point1") ;
      game.addMessage("unicorn",10,"$Brief_2_1") ;
      game.addMessageLater("helper",10,10,"$Brief_2_2") ;
      game.addNewTask("findmachine","$Task2") ;
    }
  }

  if (game.isUnitExist(uidm1)) {
    if (game.isUnitNearXY(uidhero,27,2)) {
      game.deleteUnitLater(uidm1) ;
      game.addMachine(27,2) ;
      find_count++ ;
    }
  }

  if (game.isUnitExist(uidm2)) {
    if (game.isUnitNearXY(uidhero,58,1)) {
      game.deleteUnitLater(uidm2) ;
      game.addMachine(58,1) ;
      find_count++ ;
    }
  }

  if (game.isUnitExist(uidm3)) {
    if (game.isUnitNearXY(uidhero,4,20)) {
      game.deleteUnitLater(uidm3) ;
      game.addMachine(4,20) ;
      find_count++ ;
    }
  }

  if ((find_count==3)&&(!game.isFlag("findall"))) {
    game.setFlag("findall") ;
    game.setTaskCompleted("findmachine") ;
    game.addMessage("unicorn",10,"$Brief_M") ;
  }

  if (!game.isFlag("point2")) {
    if (game.isUnitNearXYDist(uidhero,56,37,4)) {
      game.setFlag("point2") ;
      game.addMessage("unicorn",10,"$Brief_3") ;
    }
  }
}

function isVictory() {
  return game.isFlag("point2") ;
}

function isDefeat() {
  if (game.getCountByComponent("Unicorn")==0) { return true ; }
  return false ;
}
