var game ;
var MANA_TASK ;
var TIME_LIMIT ;
 
function initMap() {
  game = new Game() ;

  MANA_TASK = 2000;
  if (game.isHard1()) { MANA_TASK+=2000 ; }
  if (game.isHard2()) { MANA_TASK+=2000 ; }

  TIME_LIMIT = 8 ;

  game.allowAction("MakeHarvester") ;
  game.allowAction("MakeAttacker") ;
  game.allowAction("MakeHealer") ;
  game.allowAction("MakeRadar") ;
  game.allowAction("DoRadar") ;
  game.allowAction("UpgradeHarvester") ;
  game.allowAction("UpgradeAttacker") ;
  game.allowAction("UpgradeHealer") ;
  game.allowAction("MakeShield") ;
  game.allowAction("DoShield") ;
  game.allowAction("MakeTowerAttack") ;
  game.allowAction("MakeTowerHealer") ;
  game.allowAction("MakeTowerHarvest") ;
  game.allowAction("BuildUnicorn") ;
  game.allowAction("ResearchWorkInAction") ;
  game.allowAction("ResearchMagicEconomy") ;
  game.allowAction("ConstructMachine") ;

  game.addPortal(14,4) ;
  game.addAcademy(18,5) ;
  game.addMachinary(10,6) ;
  game.addUnicorn(14,7) ;
  game.addCrystal(10,12,300) ;
  game.addCrystal(20,13,450) ;
  game.addCrystal(4,23,530) ;
  game.addCrystal(25,27,760) ;
  game.addCrystal(4,37,470) ;
  game.addCrystal(28,40,810) ;
  game.addCrystal(19,43,890) ;
  game.addCrystal(17,45,970) ;
  game.addCrystal(15,48,1200) ;
  game.addCrystal(13,49,1600) ;
  game.addCrystal(16,50,2400) ;

  game.addEnemy1(8,22) ;
  game.addEnemy1(23,24) ;

  game.addEnemy1(14,36) ;
  game.addEnemy1(13,33) ;
  game.addEnemy1(15,32) ;
  game.addEnemy2(14,34) ;

  game.addEnemy1(15,53) ;
  game.addEnemy1(16,52) ;
  game.addEnemy1(17,54) ;
  game.addEnemy1(14,56) ;
  game.addEnemy2(13,53) ;
  game.addEnemy2(15,54) ;
  game.addEnemy3(14,52) ;

  game.incEnergy(200) ;

  game.startTimer(TIME_LIMIT*60) ;

  game.setNewViewPoint(14,6) ;

  game.addMessage("unicorn",10,String::format(game.getText("Brief_1_1"),MANA_TASK)) ;
  game.addMessageLater("unicorn",10,10,"$Brief_1_2") ;
  game.addNewTask("collect",String::format(game.getText("Task"),MANA_TASK,TIME_LIMIT)) ;

  return true ;
}

function Update() {
}

function isVictory() {
  return (game.getEnergy()>=MANA_TASK) ;
}

function isDefeat() {
  if ((game.getCountByComponent("Unicorn")==0)&&
      (game.getCountByComponent("Portal")==0)) { return true ; }
  if (game.getTimer()<=0) { return true ; }
  return false ;
}
