var game ;
var uidhero ;
 
function initMap() {
  game = new Game() ;

  game.allowAction("MakeHarvester") ;
  game.allowAction("MakeAttacker") ;
  game.allowAction("MakeHealer") ;
  game.allowAction("MakeRadar") ;
  game.allowAction("DoRadar") ;
  game.allowAction("UpgradeHarvester") ;
  game.allowAction("UpgradeAttacker") ;
  game.allowAction("UpgradeHealer") ;
  game.allowAction("MakeShield") ;
  game.allowAction("DoShield") ;
  game.allowAction("MakeTowerAttack") ;
  game.allowAction("MakeTowerHealer") ;
  game.allowAction("MakeTowerHarvest") ;

  game.addPortal(56,37) ;
  uidhero = game.addUnicorn(3,3) ;
  game.addCrystal(36,9,43) ;
  game.addCrystal(11,15,78) ;
  game.addCrystal(56,24,56) ;

  game.addMachine(27,2) ;

  game.addEnemy1(47,12) ;
  game.addEnemy1(33,22) ;
  game.addEnemy1(5,30) ;

  game.addEnemy1(40,35) ;
  game.addEnemy1(42,34) ;
  game.addEnemy1(37,34) ;
  game.addEnemy1(40,38) ;
  game.addEnemy2(42,36) ;
  game.addEnemy2(38,37) ;

  game.incEnergy(100) ;

  game.setNewViewPoint(8,5) ;

  game.addMessage("unicorn",10,"$Brief_1") ;
  game.addNewTask("findportal","$Task1") ;
  return true ;
}

function Update() {
  if (!game.isFlag("point1")) {
    if (game.isUnitNearXYDist(uidhero,27,2,3)) {
      game.setFlag("point1") ;
      game.addMessage("unicorn",10,"$Brief_2_1") ;
      game.addMessageLater("helper",10,10,"$Brief_2_2") ;
      game.addNewTask("findmachine","$Task2") ;
    }
  }

  if (!game.isFlag("point2")) {
    if (game.isUnitNearXYDist(uidhero,56,37,4)) {
      game.setFlag("point2") ;
      game.addMessage("unicorn",10,"$Brief_3") ;
    }
  }
}

function isVictory() {
  return game.isFlag("point2") ;
}

function isDefeat() {
  if (game.getCountByComponent("Unicorn")==0) { return true ; }
  return false ;
}
