var game ;
var uidrich ;
 
function initMap() {
  game = new Game() ;

  game.allowAction("MakeHarvester") ;
  game.allowAction("MakeAttacker") ;
  game.allowAction("MakeHealer") ;
  game.allowAction("MakeRadar") ;
  game.allowAction("DoRadar") ;
  game.allowAction("UpgradeHarvester") ;
  game.allowAction("UpgradeAttacker") ;
  game.allowAction("UpgradeHealer") ;
  game.allowAction("MakeShield") ;
  game.allowAction("DoShield") ;
  game.allowAction("MakeTowerAttack") ;
  game.allowAction("MakeTowerHealer") ;
  game.allowAction("MakeTowerHarvest") ;
  game.allowAction("BuildUnicorn") ;
  game.allowAction("ResearchWorkInAction") ;
  game.allowAction("ResearchMagicEconomy") ;
  game.allowAction("ConstructMachine") ;
  game.allowAction("IncreaseUnicornCount") ;
  game.allowAction("ResearchFastBuild") ;
  game.allowAction("SetupBaseShield") ;
  game.allowAction("BuildAcademy") ;
  game.allowAction("BuildMachinary") ;

  game.addPortal(13,32) ;

  uidrich = game.addCrystalRich(37,37,6000) ;
  game.addLair(10,6,"4a") ;
  game.addLair(11,11,"3a3a3b") ;
  if (game.isHard1()) {
    game.addLair(16,8,"3a3a3a3b3b3c3c") ;
  }

  game.incEnergy(400) ;

  game.setNewViewPoint(13,32) ;

  if (game.isHard2()) {
    game.addMessage("unicorn",10,"$Brief_1_1_Hard2") ;
  }
  else {
    game.addMessage("unicorn",10,"$Brief_1_1") ;
  }
  game.addMessageLater("unicorn",10,10,"$Brief_1_2") ;

  game.addNewTask("rich","$MainTask") ;
  if (game.isHard2()) {
    game.addNewTask("amount","$ManaTask") ;
  }
  game.addNewTask("caves","$SecondTask") ;

  return true ;
}

function Update() {
  if ((game.getCountByComponent("EnemyLair")==0)&&
     (!game.isFlag("nocaves"))) {
     game.setFlag("nocaves") ;
     game.setTaskCompleted("caves") ;
     game.addMessage("unicorn",10,"$Brief_2") ;
  }

  if ((!game.isUnitExist(uidrich))&&(!game.isFlag("rich"))) {
     game.setFlag("rich") ;
     if (game.isHard2()) {
       if (game.getEnergy()>=10000) {
         game.setFlag("win") ;
         game.addMessage("unicorn",10,"$Brief_3_Win") ;
       }
       else {
         game.setFlag("fail") ;
         game.addMessage("unicorn",10,"$Brief_3_Fail") ;
       }
     }
     else {
       game.setFlag("win") ;
       game.addMessage("unicorn",10,"$Brief_3") ;
     }
  }
}

function isVictory() {
  return game.isFlag("win") ;
}

function isDefeat() {
  if ((game.getCountByComponent("Unicorn")==0)&&
      (game.getCountByComponent("Portal")==0)) { return true ; }
  if (game.isFlag("fail")) { return true ; }
  return false ;
}
