var game ;

var TIME_LIMIT ;

function initMap() {
  game = new Game() ;

  TIME_LIMIT = 6 ;

  game.addPortal(20,5) ;
  game.addUnicorn(24,6) ;
  game.addUnicorn(23,7) ;
  game.addCrystal(12,3,750) ;
  game.addCrystal(10,10,630) ;
  game.addEnemy2(9,4) ;
  game.addEnemy3(9,8) ;
  game.addEnemy2(8,10) ;
  game.addLair(4,5,"a") ;
  game.addLair(6,9,"a") ;

  game.incEnergy(800) ;
  game.setTaskText(String::format("Очистите зараженную местность\nза {0} минут\nи не дайте разрушить портал!",TIME_LIMIT)) ;

  game.startTimer(TIME_LIMIT*60) ;

  game.setNewViewPoint(23,5) ;

  return true ;
}

function isVictory() {
  return !game.isMushroomsExist() ;
}

function isDefeat() {
  if (game.getCountByComponent("Portal")==0) { return true ; }
  if (game.getTimer()<=0) { return true ; }
  return false ;
}
